py-svn: delete because I don't want to maintain it.
1) We don't use py-svn named ports now.
2) I don't want to support it in py-pysvn with an older version with a
   potentially different patch then the most current version uses.
3) It's Python 2.4 ;)
4) The package being deleted currently fails to build with the
   following error:

Compile pysvn_client_cmd_diff.o
g++ -c -Wall -no-long-double -fPIC -fexceptions -frtti -I/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_release_ports_python_py-svn/py-svn/work/pysvn-1.7.5/Import/pycxx-6.2.2 -I/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_release_ports_python_py-svn/py-svn/work/pysvn-1.7.5/Import/pycxx-6.2.2/Src -I/opt/local/include/python2.4 -I/opt/local/include/subversion-1 -I/opt/local/include/apr-1 -I. -DNDEBUG -DDARWIN -DPYCXX_PYTHON_2TO3 -Dinit_pysvn=init_pysvn_2_4 -Dinit_pysvn_d=init_pysvn_2_4_d   -o pysvn_client_cmd_diff.o pysvn_client_cmd_diff.cpp
pysvn_client_cmd_checkin.cpp: In member function ‘Py::Object pysvn_client::cmd_checkin(const Py::Tuple&, const Py::Dict&)’:
pysvn_client_cmd_checkin.cpp:130: warning: ‘svn_client_commit’ is deprecated (declared at /opt/local/include/subversion-1/svn_client.h:2054)
pysvn_client_cmd_checkin.cpp:137: warning: ‘svn_client_commit’ is deprecated (declared at /opt/local/include/subversion-1/svn_client.h:2054)
pysvn_client_cmd_checkin.cpp: In member function ‘Py::Object pysvn_client::cmd_checkout(const Py::Tuple&, const Py::Dict&)’:
pysvn_client_cmd_checkin.cpp:241: warning: ‘svn_client_checkout’ is deprecated (declared at /opt/local/include/subversion-1/svn_client.h:1173)
pysvn_client_cmd_checkin.cpp:250: warning: ‘svn_client_checkout’ is deprecated (declared at /opt/local/include/subversion-1/svn_client.h:1173)
pysvn_client_cmd_checkin.cpp: In member function ‘Py::Object pysvn_client::cmd_resolved(const Py::Tuple&, const Py::Dict&)’:
pysvn_client_cmd_checkin.cpp:349: warning: ‘svn_client_resolved’ is deprecated (declared at /opt/local/include/subversion-1/svn_client.h:3731)
pysvn_client_cmd_checkin.cpp:355: warning: ‘svn_client_resolved’ is deprecated (declared at /opt/local/include/subversion-1/svn_client.h:3731)
pysvn_client_cmd_checkin.cpp: In member function ‘Py::Object pysvn_client::cmd_update(const Py::Tuple&, const Py::Dict&)’:
pysvn_client_cmd_checkin.cpp:440: warning: ‘svn_client_update’ is deprecated (declared at /opt/local/include/subversion-1/svn_client.h:1320)
pysvn_client_cmd_checkin.cpp:448: error: cannot convert ‘apr_array_header_t**’ to ‘svn_revnum_t*’ for argument ‘1’ to ‘svn_error_t* svn_client_update(svn_revnum_t*, const char*, const svn_opt_revision_t*, svn_boolean_t, svn_client_ctx_t*, apr_pool_t*)’
make: *** [pysvn_client_cmd_checkin.o] Error 1
make: *** Waiting for unfinished jobs....


git-svn-id: https://svn.macports.org/repository/macports/trunk@96754 d073be05-634f-4543-b044-5fe20cf6d1d6